### ISSUE TITLE
Awesome Project 

### ISSUE THREAD

**Issue by AcidRain9** [divinity76/msgme#7]
Wow amazing project, most of the code flew over my head😵‍💫 you are a really talented developer. I'm trying to understand how it all works but It's very complex for me. If you have some spare time can you help me, first I'm trying to understand how login system works and after that try to understand how the messaging system work

Can you just provide me with the part that does the login?
I looked into the facebook.relay.php but it's connected with other parts, so I'm having a hard time

Thanks

**Comment by divinity76** [comment]
the login function is under `function __construct()` in src/php/relays/facebook.relay.php here https://github.com/divinity76/msgme/blob/master/src/php/relays/facebook.relay.php#L86

i developed it by inspecting the login procedure with [Fiddler Proxy](https://www.telerik.com/download/fiddler)

unfortunately Facebook has broken the login code, and it needs to be updated. but i don't have time to update it now. but with a bit of luck, maybe you can figure it out ^^ glhf

**Comment by AcidRain9** [comment]
Yeah I need all the luck I can, if you think I can figure it out. But I'll give it a shot

**Comment by divinity76** [comment]
@AcidRain9 update: just fixed it, login/message sending works again now :) see the changes to `src/php/relays/facebook.relay.php`  in 7df651b822d8b1e12782b11be6eeafa1db3499f8
