### ISSUE TITLE
How to run it on ftp?

### ISSUE THREAD

**Issue by gary00k** [divinity76/msgme#8]
Hello,
How to use it? I edited FB account's data, uploaded it on ftp, but don't know what next.

**Comment by divinity76** [comment]
@gary00k you need to login via ssh to actually run it on whatever server you uploaded it to.

maybe this guide can help you to the basics of ssh: https://www.digitalocean.com/community/tutorials/ssh-essentials-working-with-ssh-servers-clients-and-keys

alternatively, the people over at irc://irc.libera.chat:6697/#linux may be able to help you, if you have a irc client
